apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: connect-haproxy-operator
    app.kubernetes.io/managed-by: kustomize
  name: manager-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups:
    - networking.k8s.io
  resources:
      - ingresses
  verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
